FROM jupyter/base-notebook

WORKDIR /app

# Instalar bibliotecas
#RUN pip install pipreqs
#RUN pipreqs .
#RUN pip install -r ./requirements.txt

#RUN pip install -r ./requirements.txt
#RUN pip install -r /core/requirements.txt
